apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: soulgarden
  labels:
    app: api-gateway
data:
  application.yml: |-
    spring:
      application:
        name: api-gateway
    
      cloud:
        gateway:
          routes:
            - id: auth-service
              uri: http://auth:80
              predicates:
                - Path=/auth/public/**
                - Method=GET,POST
              filters:
                - RewritePath=/user/public/(?<remaining>.*),/${remaining}
