apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: soulgarden
  labels:
    app: api-gateway
data:
  application.yml: |-
    spring:
      application:
        name: api-gateway
    
      cloud:
        gateway:
          server:
            webflux:
              routes:
                - id: auth-service
                  uri: http://auth-serice:80
                  predicates:
                    - Path=/auth/public/**
                    - Method=GET,POST,DELETE
                  filters:
                    - RewritePath=auth/public/(?<remaining>.*),/${remaining}
