apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: soulgarden
  labels:
    app: log-service
spec:
  selector:
    app: log-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP