spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: auth-service
            uri: http://auth-service:80
            predicates:
              - Path=/auth/public/**
              - Method=GET,POST,DELETE
            filters:
              - RewritePath=/auth/public/(?<remaining>.*), /${remaining}

