apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../back/services/api-gateway/k8s
  - ../back/services/auth-service/k8s
  - ../back/infrastructures/kafka
  - ../back/infrastructures/redis
  - ../back/infrastructures/elasticsearch